name: date_range_picker
description: Date Range Pickers use a dialog window to select a range of date on mobile.
version: 1.0.6
author: anicdh <anic.dh@gmail.com>
homepage: https://github.com/anicdh/date_range_picker

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_web_compilers: '>=1.0.0 <2.0.0'

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui